### PR TITLE
Update missing docs and adding JS/TS support in React

### PR DESCRIPTION
**Pull request by AlphaByte-RedTeam**
**Did you build the project before submitting the PR?**

- [ ] Yes
- [x] No

### CODE REVIEW

**Review by matteobruni — APPROVED** [review]
Looks good to me

**Comment by matteobruni** [comment]
@AlphaByte-RedTeam your branch is not updated to the latest commit, I think this condition will last for a few hours since all the open PR about `terser` package. Try to update your branch tomorrow. Everything looks fine though, good job!

**Comment by AlphaByte-RedTeam** [comment]
thanks a lot

**Comment by matteobruni** [comment]
Whenever you want you can update branch and this will be merged

**Pull request merged**
