### PR TITLE
fix: Spelling Correction

### PR DESCRIPTION
**Pull request by Gulshanaggarwal**
**Did you build the project before submitting the PR?**

Yes, I have done  with set-up locally & looking to take deep dive into it.

### CODE REVIEW

**Comment by Gulshanaggarwal** [comment]
Hey @matteobruni I have just fixed a spelling correction. I'm just starting with the project & looking to make quality contributions very soon.

__
[sema-logo](https://semasoftware.com/gh) &nbsp;**Summary:** :hammer_and_wrench: This code needs a fix

**Review by matteobruni — CHANGES_REQUESTED** [review]
This is a placeholder text, it's not necessary to review it, there should be placed something more inherent to the project instead of a SpiderMan reference.

**Comment by Gulshanaggarwal** [comment]
Ok, @matteobruni I got your point. You mean I should replace the placeholder content to some actual content? Although I'm little confused how I can help in building this website ? 

__
[sema-logo](https://semasoftware.com/gh) &nbsp;**Summary:** :question: I have a question

**Comment by matteobruni** [comment]
> Ok, @matteobruni I got your point. You mean I should replace the placeholder content to some actual content? Although I'm little confused how I can help in building this website ?
> 
> __ [sema-logo](https://semasoftware.com/gh) [ sema-logo ](https://semasoftware.com/gh) [ ](https://semasoftware.com/gh)  **Summary:** ❓ I have a question

As I said in the other PR, the placeholder content needs to be replaced, also the new website is lacking a gallery of presets, and samples (starting from a thumbnail or a small image) a new webpage will be opened containing a working sample with code that can be toggled (like <https://confetti.js.org/>). Anyway the new website is in a really early stage, be creative.
I didn't spent much time about the new website layout, I'd like to release 2.2.0 (PR #4341) this week so I'm working on the codebase and not on the website, so you are free to make any kind of change for the better.

**Pull request closed without merging**
