### PR TITLE
Suggest french translation for vue readme

### PR DESCRIPTION
**Pull request by ManuSquall**
Suggest french translation for [vue3 readme file](https://github.com/matteobruni/tsparticles/tree/main/components/vue) readme file

**Did you build the project before submitting the PR?**

- [ ] Yes
- [X] No

### CODE REVIEW

**Review by matteobruni — CHANGES_REQUESTED** [review]
Waiting for the other translation to be merged here

**Review by matteobruni — CHANGES_REQUESTED** [review]
I've seen that `vue3-alt` is missing, can you update that as well? I don't want it to feel alone 😉

**Comment by ManuSquall** [comment]
I usually do one PR per file that I translate on other projects, it's easier afterwards to correct / discuss about typos if there are any, but yes, on my way 🙂

**Comment by matteobruni** [comment]
Looks good to me, thanks

**Pull request merged**
