### PR TITLE
Add Testing Structure and Tests for Utils.ts

### LINKED ISSUE #229: Add unit tests
This project is becoming huge and some unit tests could improve testing process.

The critical tests are about options that are a lot and have a lot of values and some properties can have different values.

Some tests about `tsParticles` initializer can be made too, or something about the core functionalities.

For options `mocha` and `chai` seem fine, about the animation process I really don't know if they can be used.

### PR DESCRIPTION
**Pull request by PieceMaker**
This set of changes contains the beginning structure for testing, as well as a set of tests for the `Utils.ts` class. The tests use mocha, chai, and ts-node.

The tests for `Utils.ts` cover all methods except `getParticleBaseVelocity` and `loadFont`. There is one skipped test that is currently failing. I believe this test is failing due to a bug in `isInArray`. When using numeric arrays in t his function, if `array` is a number and not a numeric array, the function throws the error `TypeError: array.indexOf is not a function`.

### CODE REVIEW

**Comment by matteobruni** [comment]
Please target dev branch, there’s already an options test there and the commands ready for CI

< https://github.com/matteobruni/tsparticles/blob/master/CONTRIBUTING.md#pull-requests>

**Review by matteobruni — CHANGES_REQUESTED** [review]
Please target dev branch, there’s already an options test there and the commands ready for CI

<https://github.com/matteobruni/tsparticles/blob/master/CONTRIBUTING.md#pull-requested>

**Comment by PieceMaker** [comment]
My bad. I read that in the contrib and then completely forgot. It looks like you already changed it. I'll make sure to target dev in the future.

I made a couple of small changes to follow the structure in dev.

**Review by matteobruni — APPROVED** [review]
Needed an update from `dev`

**Comment by matteobruni** [comment]
Everything seems good

**Pull request merged**
